[package]

name = "bio"
version = "0.11.0"
authors = ["Johannes Köster <johannes.koester@tu-dortmund.de>"]
description = "A bioinformatics library for Rust. This library provides implementations of many algorithms and data structures that are useful for bioinformatics, but also in other fields."
homepage = "http://rust-bio.github.io"
repository = "https://github.com/rust-bio/rust-bio"
documentation = "https://rust-bio.github.io/rust-bio/bio/index.html"
readme = "README.md"
license = "MIT"

[features]
nightly = ["serde", "serde_macros", "vec_map/eders"]

[dependencies]
csv = "0.15.*"
rustc-serialize = "0.3.*"
num-traits = "0.1.*"
num-integer = "0.1.*"
itertools = "0.5.*"
itertools-num = "0.1.*"
bit-vec = "0.4.*"
vec_map = "0.6.*"
bit-set = "0.4.*"
nalgebra= "0.10.*"
lazy_static = "0.2.*"
serde = { version = "0.6", optional = true }
serde_macros = { version = "0.6", optional = true }
approx = "0.1.*"
custom_derive = "0.1.*"
newtype_derive = "0.1.*"
ordered-float = "0.3.*"
quick-error = "1.1.*"
flate2 = "*"

